name: Continuously build

on:
  push:
    branches:    
      - master

jobs:
  build:

    # POM-less Tycho fails with Maven 3.6.1 and 3.6.2; installed Maven versions see:
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: Create stuff...
      run: mkdir out && echo test v26 > out/test.txt
    - name: Publish update site
      env:
        UPDATE_SITE_PATH: out
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: success()
      run: |
        mkdir "${HOME}/target_repo"
        cd "${HOME}/target_repo"
        git clone --no-checkout --depth 1 "file://${GITHUB_WORKSPACE}" .
        echo "--- after clone: ---"
        ls -ls
        echo "--------------------"
        git remote add github "https://github.com/${GITHUB_REPOSITORY}"
        if [ "`git ls-remote --heads github update-site`" ]; then git fetch --depth=1 github update-site; fi
        echo "--- after fetch: ---"
        ls -ls
        echo "--------------------"
        if [ "`git branch -r --list github/update-site`" ]
        then
          git checkout -t github/update-site
        else
          git checkout --orphan update-site
        fi
        echo "--- after checkout: ---"
        ls -ls
        echo "-----------------------"
        rm -rf staging
        cp -av "${GITHUB_WORKSPACE}/${UPDATE_SITE_PATH}" staging
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --local user.name  "${GITHUB_ACTOR}"
        git add staging
        if [ "`git branch -r --list github/update-site`" ]
        then
          git commit --amend -m "Update update site"
        else
          git commit -m "Update update site"
        fi
        git push --force "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:update-site
        echo "Done. See: https://github.com/${GITHUB_REPOSITORY}/blob/update-site/staging"
        echo "Update site: https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/update-site/staging"
