name: Continuously build

on:
  push:
    branches:    
      - master

jobs:
  build:

    # POM-less Tycho fails with Maven 3.6.1 and 3.6.2:
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: Create stuff...
      run: mkdir out && echo test v6 > out/test.txt
    - name: Publish update site
      env:
        UPDATE_SITE_PATH: out
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: success()
      run: |
        mkdir "${HOME}/target_repo"
        cd "${HOME}/target_repo"
        echo ">>>>> 1/6 Clone locally"
        git clone "file://${GITHUB_WORKSPACE}" . --no-checkout --no-single-branch --depth 1
        #if [ `git branch -r --contains update-site` ]; then git checkout update-site; else git checkout --orphan update-site; fi
        #git checkout --orphan update-site
        #git checkout -b update-site
        if [ `git branch -r --contains update-site` ]
        then
          echo ">>>>> 2/6 Create new 'update-site' branch"
          git checkout --orphan update-site
          echo End without update-site branch
        else
          echo ">>>>> 2/6 Checkout remote 'update-site' branch"
          git checkout -b update-site
          echo End with update-site branch
        fi
        echo ">>>>> 3/6 Get update site"
        rm -rf staging
        cp -av "${GITHUB_WORKSPACE}/${UPDATE_SITE_PATH}" staging
        echo ">>>>> 4/6 Add"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --local user.name  "${GITHUB_ACTOR}"
        git add staging
        #if [ `git branch -r --contains update-site` ]; then git commit --amend -m "Update update site"; else git commit -m "Update update site"; fi
        #git commit -m "Update update site"
        #git commit --amend -m "Update update site"
        if [ `git branch -r --contains update-site` ]
        then
          echo ">>>>> 5/6 Create initial commit"
          git commit -m "Update update site"
          echo End without update-site branch
        else
          echo ">>>>> 5/6 Update last commit (using '--amend')"
          git commit --amend -m "Update update site"
          echo End with update-site branch
        fi
        echo ">>>>> 6/6 Push to https://github.com/${GITHUB_REPOSITORY}.git"
        #git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:update-site
        git push --force "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:update-site
        echo Done.
        echo "See: https://github.com/${GITHUB_REPOSITORY}/blob/update-site/staging"
        echo "Update site: https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/update-site/staging"
